version: '3.8'

services:
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - "8082:8082"
    volumes:
      - ./services/nginx/conf.d/${ENV}:/etc/nginx/conf.d
      - ./services/nginx/logs:/var/log/nginx
      - ${SSL_PATH}:/etc/nginx/ssl
    networks:
      tourismania_network:
        ipv4_address: ${SUBNET_NGINX_IP}
    depends_on:
      - web

  web:
    build:
      context: ${WEB_PATH}/
      dockerfile: Dockerfile
      target: ${WEB_ENV}
    networks:
      - tourismania_network

  api:
    build:
      context: ${API_PATH}/
      dockerfile: Dockerfile
      target: frankenphp_prod
    environment:
      SERVER_NAME: ${API_SERVER_NAME}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    expose:
      - 8080
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./services/api/jwt:/app/config/jwt:rw
    networks:
      - tourismania_network

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: tourismania
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./services/postgres/data:/var/lib/postgresql/data
    networks:
      - tourismania_network

  kafka:
    image: apache/kafka:4.1.0
    expose:
      - "9092" # для внешних потребителей (продюсеры, консумеры, kafka-ui)
      - "9093" # для управления методанными (kraft)
    environment:
      # Основные настройки KRaft
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      # Настройка слушателей
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER

      # Прочие настройки
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      #- ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./services/kafka/data:/var/lib/kafka/data:rw
    networks:
      - tourismania_network

  # akhq - web для kafka
  kafka-ui:
    image: tchiotludo/akhq:latest
    depends_on:
      - kafka
    expose:
      - "8080"
    environment:
      # Основная конфигурация AKHQ
      AKHQ_CONFIGURATION: |
        micronaut:
          security:
            enabled: true
        akhq:
          connections:
            kafka-local:
              properties:
                bootstrap.servers: "kafka:9092"
          server:
            access-log:
              enabled: true
          pagination:
            page-size: 25
          ui:
            default-view: topics
          security:
            default-group: no-roles
            basic-auth:
              - username: admin
                password: "${KAFKA_ADMIN_PASSWORD}"
                groups:
                - admin
              - username: reader
                password: "${KAFKA_READER_PASSWORD}"
                groups:
                - reader

    networks:
      - tourismania_network

volumes:
  caddy_data:
  caddy_config:

networks:
  tourismania_network:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
